services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: chatapp-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"   # Host 3000 → container 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: chatapp-backend
    restart: unless-stopped
    ports:
      - "8090:8081"   # Host 8090 → container 8081 
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
  mongo:
    image: mongo:6
    container_name: chatapp-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
