name: Deploy Full-stack ChatApp

env:
  SSH_PORT: 2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  backend-build-and-deploy:  # ------------- backend deployment -------------
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Setup Java and Maven
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Build backend
      - name: Build backend
        run: |
          cd backend
          mvn clean package -DskipTests

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # Retrieve the fingerprint and store it in the GitHub Actions VM's known_hosts file.
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts

      # Copy published files to server
      - name: Deploy backend files 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/chatapp/backend/"
          scp -P $SSH_PORT backend/target/chatappjn-0.0.1-SNAPSHOT.jar barry75@barryonweb.com:/var/www/chatapp/backend/
          scp -P $SSH_PORT backend/startProd.sh barry75@barryonweb.com:/var/www/chatapp/backend/

      # Deploy application.yaml config
      - name: Deploy Spring config file
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/chatapp/backend/config/"
          scp -P $SSH_PORT backend/src/main/resources/application.yaml barry75@barryonweb.com:/var/www/chatapp/backend/config/
      
      # Deploy Nginx config and reload
      - name: Update Nginx config
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/chatapp/nginx/"
          scp -P $SSH_PORT chatapp-dev.barryonweb.com barry75@barryonweb.com:/var/www/chatapp/nginx/
          ssh -p $SSH_PORT barry75@barryonweb.com "
            sudo cp /var/www/chatapp/nginx/chatapp-dev.barryonweb.com /etc/nginx/sites-available/ &&
            sudo ln -sf /etc/nginx/sites-available/chatapp-dev.barryonweb.com /etc/nginx/sites-enabled/ &&
            sudo nginx -t && sudo systemctl reload nginx"

      # See logs after restart
      - name: Show backend logs
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "journalctl -u chatappjn.service -n 50 --no-pager"


  frontend-build-and-deploy: # ------------- frontend deployment -------------
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # GitHub - Install frontend dependencies and build
      - name: Build frontend
        run: |
          cd frontend
          npm install  
          npm run build

      # Start SSH agent with GitHub secret key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts to avoid verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts

      # Transfer frontend from GitHub Repo to Ubuntu server via SCP
      - name: Deploy frontend via SSH 
        run: |
          ssh -p $SSH_PORT barry75@barryonweb.com "mkdir -p /var/www/chatapp/frontend"
          scp -P $SSH_PORT -r frontend/dist/* barry75@barryonweb.com:/var/www/chatapp/frontend/

            # Copy Dockerfile and script to recreate Test environment container 


  test-env-containerization: # ----test environment Docker container ---------
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Start SSH agent with GitHub secret key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts to avoid verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts

      # Copy Dockerfiles and script to recreate Test environment container 
      - name: Containerize frontend Test environment 
        run: |
          scp -P $SSH_PORT frontend/Dockerfile barry75@barryonweb.com:/var/www/chatapp/frontend/
          scp -P $SSH_PORT backend/Dockerfile barry75@barryonweb.com:/var/www/chatapp/backend/
          scp -P $SSH_PORT ./runTestContainer.sh barry75@barryonweb.com:/var/www/chatapp/
  
  
  app-containerization: # ----Full stack App- Docker container ---------
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Start SSH agent with GitHub secret key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts to avoid verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts

      # Copy Dockerfiles, Docker compose and Nginx  
      - name: Containerize full stack App 
        run: |
          scp -P $SSH_PORT frontend/Dockerfile.prod barry75@barryonweb.com:/var/www/chatapp/frontend/
          scp -P $SSH_PORT backend/Dockerfile.prod barry75@barryonweb.com:/var/www/chatapp/backend/
          scp -P $SSH_PORT ./docker-compose.yml  barry75@barryonweb.com:/var/www/chatapp/
          scp -P $SSH_PORT nginx/chatapp-docker.conf  barry75@barryonweb.com:/var/www/chatapp/nginx/

  